swtpm_setup: Switch over to new python tool and get rid of the bash script
Switch over to the new python implementation of swtpm_setup. We need to
also adjust test cases that involved the tcsd that otherwise fail for
various reasons. For in-place testing we need to adjust the PYTHONPATH
and PATH so that swtpm_setup.py can be found and so that swtpm_setup.py
then finds swtpm if it is not explicitly passed as parameter.

Adjust the man page for swtpm_setup to reflect the changes.

We now can run swtpm_setup as any user. However, libvirt still runs it
as tss:tss (for example), which is then creating the signing key as tss:tss
as well. Ideally libvirt would run it as tss:root or any other combination
since the tss group may be used for user wanting to access /dev/tpmrm0 for
example. We at least change the directory ownership of /var/lib/swtpm-localca
to tss:root and keep the world out of this directory.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

diff --git a/src/swtpm_setup/Makefile.am b/src/swtpm_setup/Makefile.am
--- a/src/swtpm_setup/Makefile.am
+++ b/src/swtpm_setup/Makefile.am
@@ -4,9 +4,6 @@
 # For the license, see the LICENSE file in the root directory.
 #
 
-noinst_HEADERS = \
-	swtpm_setup.h
-
 bin_PROGRAMS = \
 	swtpm_setup
 
@@ -14,7 +11,54 @@ swtpm_setup_SOURCES = swtpm_setup.c
 
 dist_bin_SCRIPTS = swtpm_setup.sh
 
+PY_SWTPM_SETUP_FILES = $(wildcard py_swtpm_setup/*.py)
+
+PY_PACKAGE_NAME=swtpm_setup
+PY_PACKAGE_NV=$(PY_PACKAGE_NAME)-$(SWTPM_VER_MAJOR).$(SWTPM_VER_MINOR).$(SWTPM_VER_MICRO)
+PY_PACKAGE=dist/$(PY_PACKAGE_NV).tar.gz
+
+# for out-of-tree builds we need to copy setup.py
+$(PY_PACKAGE): $(PY_SWTPM_SETUP_FILES)
+	@$(CP) $(srcdir)/setup.py ./ &>/dev/null || true
+	./setup.py sdist
+
+all-local: $(PY_PACKAGE)
+
+# for in-tree testing on Cygwin we need to copy swtpm_setup.exe
+# for it to find swtpm_setup.sh
+all:
+	@if test "$(host_os)" = "cygwin"; then \
+		$(CP) -f .libs/swtpm_setup.exe ./ ; \
+	fi
+
+install-exec-local: $(PY_PACKAGE)
+	@if ! test $(findstring /usr, "$(DESTDIR)$(bindir)"); then \
+		echo "Warning: Not installing python package to $(DESTDIR)$(bindir)"; \
+	else \
+		echo "Installing python to DESTDIR '/$(DESTDIR)'"; \
+		./setup.py install --prefix=$(prefix) --root "/$(DESTDIR)" --install-layout deb 2>/dev/null || \
+		./setup.py install --prefix=$(prefix) --root "/$(DESTDIR)" 2>/dev/null ; \
+	fi
+
+uninstall-local:
+	@if ! test $(findstring /usr, "$(DESTDIR)$(bindir)"); then \
+		echo "Cleanup for distcheck build not implemented" ; \
+	else \
+		echo "Local pip3 uninstall"; \
+		$(PIP3) uninstall -y $(PY_PACKAGE_NAME); \
+	fi
+
+# for out-of-tree builds we need to clean up
+clean-local:
+	if test "$(top_srcdir)" != "$(top_builddir)"; then \
+		rm -f setup.py; \
+	fi
+	rm -rf py_swtpm_setup/__pycache__/
+	rm -rf swtpm_setup.egg-info/
+	rm -rf dist
+
 EXTRA_DIST = \
+	setup.py \
 	README
 
 CLEANFILES = *.gcno *.gcda *.gcov
