swtpm_setup: create a storage primary key
Create a storage primary key and print the handle of the created key.

Signed-off-by: Stefan Berger <stefanb@linux.vnet.ibm.com>

diff --git a/src/swtpm_setup/swtpm_setup.sh.in b/src/swtpm_setup/swtpm_setup.sh.in
--- a/src/swtpm_setup/swtpm_setup.sh.in
+++ b/src/swtpm_setup/swtpm_setup.sh.in
@@ -79,8 +79,8 @@ SETUP_STATE_NOT_OVERWRITE_F=256
 SETUP_TPM2_F=512
 SETUP_ALLOW_SIGNING_F=1024
 SETUP_TPM2_ECC_F=2048
-
-SETUP_DISPLAY_RESULTS_F=4096
+SETUP_CREATE_SPK_F=4096
+SETUP_DISPLAY_RESULTS_F=8192
 
 # default values for passwords
 DEFAULT_OWNER_PASSWORD=ooo
@@ -109,6 +109,7 @@ TPM2_NV_INDEX_PlatformCert=$((0x01c08000))
 
 # custom option
 TPM2_EK_HANDLE=$((0x81010000))
+TPM2_SPK_HANDLE=$((0x81000000))
 
 # Default logging goes to stderr
 LOGFILE=""
@@ -855,6 +856,33 @@ tpm2_createprimary_ek_rsa()
 	return $?
 }
 
+# Create a storage primary key
+#
+# @param1: flags
+tpm2_createprimary_spk_rsa()
+{
+	local flags="$1"
+
+	local symkeydata keyflags totlen publen off min_exp
+
+	# keyflags: fixedTPM, fixedParent, sensitiveDataOrigin,
+	# userWithAuth, noDA, restricted, decrypt
+	keyflags=$((0x00030472))
+	# keyflags=$((0x000300b2))
+	# symmetric: TPM_ALG_NULL
+	symkeydata='\\x00\\x06\\x00\\x80\\x00\\x43'
+	publen=$((0x1a + NONCE_RSA_SIZE))
+	totlen=$((0x43 + NONCE_RSA_SIZE))
+	min_exp=1470
+	# offset of length indicator for key
+	off=132
+
+	# TPM_RH_OWNER
+	tpm2_createprimary_rsa_params '\\x40\\x00\\x00\\x01' "${keyflags}" \
+	    "${symkeydata}" "${publen}" "${totlen}" "${min_exp}" "${off}" ""
+	return $?
+}
+
 function tpm2_createprimary_rsa_params()
 {
 	local primaryhandle="$1"
@@ -874,8 +902,8 @@ function tpm2_createprimary_rsa_params()
 	# size of buffer
 	req+='\x00\x00\x00\x09'
 	# TPM_RS_PW
-	req+='\x40\x00\x00\x09\x00\x00\x00\x00\x00\x00'
-	req+='\x04\x00\x00\x00\x00'
+	req+='\x40\x00\x00\x09\x00\x00\x00\x00\x00'
+	req+='\x00\x04\x00\x00\x00\x00'
 	# Size of TPM2B_PUBLIC
 	req+='@PUBLEN-2@'
 	# TPM_ALG_RSA, TPM_ALG_SHA256
@@ -1106,6 +1134,39 @@ tpm2_create_ek()
 	return 0
 }
 
+# Create the platform key, either RSA or ECC
+#
+# @param1: flags
+# @param2: non-evict handle, if any
+tpm2_create_spk()
+{
+	local flags="$1"
+	local nehandle="$2"
+
+	local res handle
+
+	tpm2_stirrandom
+	tpm2_changeeps
+	[ $? -ne 0 ] && return 1
+
+	res=$(tpm2_createprimary_spk_rsa "$flags")
+
+	[ $? -ne 0 ] && return 1
+
+	handle=$(echo $res | cut -d "," -f1)
+
+	# make key permanent
+	if [ -n "$nehandle" ]; then
+		tpm2_evictcontrol "$handle" "$nehandle"
+		[ $? -ne 0 ] && return 1
+	fi
+
+	# ek
+	echo $res | cut -d "," -f2-
+
+	return 0
+}
+
 # Format an integer to a represenation of '\xaa\xbb...'
 #
 # @param1: the number to format
@@ -1295,6 +1356,16 @@ init_tpm2()
 	if [ $? -ne 0 ]; then
 		logerr "swtpm_bios failed: $output"
 		return 1
+	fi
+
+	if [ $((flags & $SETUP_CREATE_SPK_F)) -ne 0 ]; then
+		pk=$(tpm2_create_spk "$flags" "${TPM2_SPK_HANDLE}")
+		if [ $? -ne 0 ]; then
+			logerr "tpm2_create_spk failed"
+			return 1
+		fi
+		logit "Successfully created storage primary key with " \
+		      "handle $(printf "0x%08x" ${TPM2_SPK_HANDLE})."
 	fi
 
 	if [ $((flags & $SETUP_CREATE_EK_F)) -ne 0 ]; then
@@ -1490,6 +1561,8 @@ The following options are supported:
 --create-platform-cert
                  : Create a platform certificate; this implies --create-ek-cert
 
+--create-spk     : Create storage primary key; this requires --tpm2
+
 --lock-nvram     : Lock NVRAM access
 
 --display        : At the end display as much info as possible about the
@@ -1545,6 +1618,7 @@ main()
 		--tpm2) flags=$((flags | SETUP_TPM2_F));;
 		--ecc) flags=$((flags | SETUP_TPM2_ECC_F));;
 		--createek) flags=$((flags | SETUP_CREATE_EK_F));;
+		--create-spk) flags=$((flags | SETUP_CREATE_SPK_F));;
 		--take-ownership) flags=$((flags |
 		                   SETUP_CREATE_EK_F|SETUP_TAKEOWN_F));;
 		--ownerpass) shift; ownerpass="$1"; got_ownerpass=1;;
@@ -1626,6 +1700,10 @@ main()
 	else
 		if [ $((flags & SETUP_TPM2_ECC_F)) -ne 0 ]; then
 			logerr "--ecc requires --tpm2."
+			exit 1
+		fi
+		if [ $((flags & SETUP_CREATE_SPK_F)) -ne 0 ]; then
+			logerr "--create-spk requires --tpm2."
 			exit 1
 		fi
 	fi
