tests: Extend encrypted state test to check for unmodified state
Extend the encrypted state test with a test case using a wrong key
for decrypting the state and make sure that the init fails and the
state files remain unmodified.

Signed-off-by: Stefan Berger <stefanb@linux.vnet.ibm.com>

diff --git a/tests/_test_save_load_encrypted_state b/tests/_test_save_load_encrypted_state
--- a/tests/_test_save_load_encrypted_state
+++ b/tests/_test_save_load_encrypted_state
@@ -275,6 +275,77 @@ if [ "$RES" != "$exp" ]; then
 	exit 1
 fi
 
+run_swtpm_ioctl ${SWTPM_INTERFACE} -s
+if [ $? -ne 0 ]; then
+	echo "Error: Could not shut down the ${SWTPM_INTERFACE} TPM."
+	echo "TPM Logfile:"
+	cat $logfile
+	exit 1
+fi
+sleep 0.5
+
+kill -0 ${SWTPM_PID} 2>/dev/null
+if [ $? -eq 0 ]; then
+	echo "Error: ${SWTPM_INTERFACE} TPM should not be running anymore."
+	echo "TPM Logfile:"
+	cat $logfile
+	exit 1
+fi
+
+echo "Test 1: Ok"
+
+# This time start we start the TPM with a wrong state encryption key
+# (key used as password) and try to start it. It has to fail and
+# the state must not have been modified.
+
+# volatile state file does not exist
+sha1_volatile=$(get_sha1_file "${VOLATILE_STATE_FILE}")
+sha1_permanent=$(get_sha1_file "${STATE_FILE}")
+echo "sha1(volatile): $sha1_volatile sha1(permanent): $sha1_permanent"
+
+run_swtpm ${SWTPM_INTERFACE} \
+	--key pwdfile=$keyfile \
+	--log file=$logfile
+
+ps aux | grep $SWTPM | grep -v grep
+
+kill -0 ${SWTPM_PID}
+if [ $? -ne 0 ]; then
+	echo "Error: ${SWTPM_INTERFACE} TPM did not start."
+	echo "TPM Logfile:"
+	cat $logfile
+	exit 1
+fi
+
+# Init the TPM
+run_swtpm_ioctl ${SWTPM_INTERFACE} -i
+if [ $? -eq 0 ]; then
+	echo "Error: ${SWTPM_INTERFACE} TPM initialization should have failed."
+	echo "TPM Logfile:"
+	cat $logfile
+	exit 1
+fi
+
+kill -0 ${SWTPM_PID} 2>/dev/null
+if [ $? -ne 0 ]; then
+	echo "Error: ${SWTPM_INTERFACE} TPM not running anymore after failed INIT."
+	echo "TPM Logfile:"
+	cat $logfile
+	exit 1
+fi
+
+if [ "${sha1_volatile}" != "$(get_sha1_file "${VOLATILE_STATE_FILE}")" ]; then
+	echo "Error: Volatile state file was modified during failed init."
+	exit 1
+fi
+
+if [ "${sha1_permanent}" != "$(get_sha1_file "${STATE_FILE}")" ]; then
+	echo "Error: Permanent state file was modified during failed init."
+	exit 1
+fi
+
+echo "Test 2: Ok"
+
 # Final shut down
 exec 100>&-
 run_swtpm_ioctl ${SWTPM_INTERFACE} -s
