tests: Shut down swtpm at the end to avoid kill
Shut down the swtpm process at the end to avoid it being killed
and with that getting noise in the test log.

Signed-off-by: Stefan Berger <stefanb@linux.vnet.ibm.com>

diff --git a/tests/_test_tpm2_probe b/tests/_test_tpm2_probe
--- a/tests/_test_tpm2_probe
+++ b/tests/_test_tpm2_probe
@@ -81,6 +81,17 @@ if [ "$RES" != "$exp" ]; then
 	exit 1
 fi
 
+run_swtpm_ioctl ${SWTPM_INTERFACE} -s
+if [ $? -ne 0 ]; then
+	echo "Error: Could not shut down the ${SWTPM_INTERFACE} TPM."
+	exit 1
+fi
+
+if wait_process_gone ${SWTPM_PID} 4; then
+	echo "Error: ${SWTPM_INTERFACE} TPM should not be running anymore."
+	exit 1
+fi
+
 echo "OK"
 
 exit 0
