tests: Extend test case to test for concurrent access to locked storage
Extend an existing test case to ensure that a 2nd swtpm process terminates
with an error related to not being able to get a lock on the storage's
lockfile.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

diff --git a/tests/_test_tpm2_save_load_state_locking b/tests/_test_tpm2_save_load_state_locking
--- a/tests/_test_tpm2_save_load_state_locking
+++ b/tests/_test_tpm2_save_load_state_locking
@@ -17,11 +17,15 @@ MY_SAVESTATE_STATE_FILE="$TPM_PATH/my.savestate"
 SWTPM_INTERFACE="${SWTPM_INTERFACE:-cuse}"
 SWTPM_CMD_UNIX_PATH="${TPM_PATH}/unix-cmd.sock"
 SWTPM_CTRL_UNIX_PATH="${TPM_PATH}/unix-ctrl.sock"
+LOGFILE="${TPM_PATH}/logfile"
 
 function cleanup()
 {
 	if [ -n "${SWTPM_PID}" ]; then
 		kill_quiet -9 "${SWTPM_PID}"
+	fi
+	if [ -n "${SWTPM2_PID}" ]; then
+		kill_quiet -9 "${SWTPM2_PID}"
 	fi
 	rm -rf "$TPM_PATH"
 }
@@ -53,6 +57,34 @@ if ! kill_quiet -0 "${SWTPM_PID}" 2>/dev/null; then
 	echo "Error: ${SWTPM_INTERFACE} TPM not running anymore after INIT."
 	exit 1
 fi
+
+# Try to start a 2nd TPM: It must not start due to the locked storage
+SWTPM_PID_SAVE=${SWTPM_PID}
+rm -f "${LOGFILE}"
+
+SWTPM_DEV_NAME="${VTPM_NAME}-2nd" \
+	SWTPM_SERVER_PORT=65484 SWTPM_CTRL_PORT=65485 \
+	SWTPM_CMD_UNIX_PATH="$TPM_PATH/2nd-cmd.sock" \
+	SWTPM_CTRL_UNIX_PATH="$TPM_PATH/2nd-ctrl.sock" \
+	SWTPM_RUN_SWTPM_WONT_START=1 \
+	run_swtpm "${SWTPM_INTERFACE}" \
+	--tpm2 \
+	--tpmstate "dir=$TPM_PATH" \
+	--log "file=${LOGFILE}" \
+	--flags not-need-init
+SWTPM2_PID="${SWTPM_PID}"
+SWTPM_PID=${SWTPM_PID_SAVE}
+
+if wait_process_gone "${SWTPM_PID2}" 4; then
+	echo "Error: ${SWTPM_INTERFACE} TPM should not be running anymore."
+	exit 1
+fi
+
+if ! grep -q "SWTPM_NVRAM_Lock_Dir: Could not lock access to lockfile" "${LOGFILE}"; then
+	echo "Error: Did not find expected error string in 2nd TPM that could not start"
+	exit 1
+fi
+
 
 # Startup the TPM
 RES=$(swtpm_cmd_tx "${SWTPM_INTERFACE}" '\x80\x01\x00\x00\x00\x0c\x00\x00\x01\x44\x00\x00')
diff --git a/tests/common b/tests/common
--- a/tests/common
+++ b/tests/common
@@ -336,6 +336,9 @@ function run_swtpm_ioctl()
 #
 # @param1: type of interface
 # @param2.. : parameters to pass to 'swtpm'
+#
+# If SWTPM_RUN_SWTPM_WONT_START is set then a start failure is expected
+# and exit will not be called.
 function run_swtpm()
 {
 	local iface=$1; shift
@@ -363,12 +366,16 @@ function run_swtpm()
 			-n "${SWTPM_DEV_NAME##*/}"
 		rc=$?
 		if [ $rc -ne 0 ]; then
-			echo "Could not run ${SWTPM_EXE} using ${iface}"
-			exit 1
+			if [ -z "${SWTPM_RUN_SWTPM_WONT_START}" ]; then
+				echo "Could not run ${SWTPM_EXE} using ${iface}"
+				exit 1
+			fi
 		fi
 		if wait_for_chardev "${SWTPM_DEV_NAME}" 2; then
-			echo "$SWTPM_DEV_NAME did not appear"
-			exit 1
+			if [ -z "${SWTPM_RUN_SWTPM_WONT_START}" ]; then
+				echo "$SWTPM_DEV_NAME did not appear"
+				exit 1
+			fi
 		fi
 
 		SWTPM_PID=$(ps aux |
@@ -403,19 +410,24 @@ function run_swtpm()
 			--ctrl "type=tcp,port=${SWTPM_CTRL_PORT}" &
 		rc=$?
 		if [ $rc -ne 0 ]; then
+			# Due to '&' above, an error means SWTPM_EXE is bad
 			echo "Could not run ${SWTPM_EXE} using ${iface}"
 			exit 1
 		fi
 		SWTPM_PID=$!
 		if wait_for_serversocket "${SWTPM_SERVER_PORT}" 127.0.0.1 2; then
-			echo "Server did not open port ${SWTPM_SERVER_PORT}"
-			kill -9 "${SWTPM_PID}"
-			exit 1
+			if [ -z "${SWTPM_RUN_SWTPM_WONT_START}" ]; then
+				echo "Server did not open port ${SWTPM_SERVER_PORT}"
+				kill -9 "${SWTPM_PID}"
+				exit 1
+			fi
 		fi
 		if wait_for_serversocket "${SWTPM_CTRL_PORT}" 127.0.0.1 1; then
-			echo "Server did not open port ${SWTPM_CTRL_PORT}"
-			kill -9 "${SWTPM_PID}"
-			exit 1
+			if [ -z "${SWTPM_RUN_SWTPM_WONT_START}" ]; then
+				echo "Server did not open port ${SWTPM_CTRL_PORT}"
+				kill -9 "${SWTPM_PID}"
+				exit 1
+			fi
 		fi
 		return 0
 		;;
@@ -444,20 +456,25 @@ function run_swtpm()
 			--ctrl "type=unixio,path=${SWTPM_CTRL_UNIX_PATH}" &
 		rc=$?
 		if [ $rc -ne 0 ]; then
+			# Due to '&' above, an error means SWTPM_EXE is bad
 			echo "Could not run ${SWTPM_EXE} using ${iface}"
 			exit 1
 		fi
 		[ $rc -ne 0 ] && return $rc
 		SWTPM_PID=$!
 		if wait_for_serversocket "${SWTPM_SERVER_PORT}" 127.0.0.1 2; then
-			echo "Server did not open port ${SWTPM_SERVER_PORT}"
-			kill -9 "${SWTPM_PID}"
-			exit 1
+			if [ -z "${SWTPM_RUN_SWTPM_WONT_START}" ]; then
+				echo "Server did not open port ${SWTPM_SERVER_PORT}"
+				kill -9 "${SWTPM_PID}"
+				exit 1
+			fi
 		fi
 		if wait_for_socketfile "${SWTPM_CTRL_UNIX_PATH}" 1; then
-			echo "Server did not create UnixIO socket ${SWTPM_CTRL_UNIX_PATH}"
-			kill -9 "${SWTPM_PID}"
-			exit 1
+			if [ -z "${SWTPM_RUN_SWTPM_WONT_START}" ]; then
+				echo "Server did not create UnixIO socket ${SWTPM_CTRL_UNIX_PATH}"
+				kill -9 "${SWTPM_PID}"
+				exit 1
+			fi
 		fi
 		return 0
 		;;
@@ -486,19 +503,24 @@ function run_swtpm()
 			--ctrl "type=tcp,port=${SWTPM_CTRL_PORT}" &
 		rc=$?
 		if [ $rc -ne 0 ]; then
+			# Due to '&' above, an error means SWTPM_EXE is bad
 			echo "Could not run ${SWTPM_EXE} using ${iface}"
 			exit 1
 		fi
 		SWTPM_PID=$!
 		if wait_for_socketfile "${SWTPM_CMD_UNIX_PATH}" 2; then
-			echo "Server did not create UnixIO socket ${SWTPM_CMD_UNIX_PATH}"
-			kill -9 "${SWTPM_PID}"
-			exit 1
+			if [ -z "${SWTPM_RUN_SWTPM_WONT_START}" ]; then
+				echo "Server did not create UnixIO socket ${SWTPM_CMD_UNIX_PATH}"
+				kill -9 "${SWTPM_PID}"
+				exit 1
+			fi
 		fi
 		if wait_for_serversocket "${SWTPM_CTRL_PORT}" 127.0.0.1 1; then
-			echo "Server did not open port ${SWTPM_CTRL_PORT}"
-			kill -9 "${SWTPM_PID}"
-			exit 1
+			if [ -z "${SWTPM_RUN_SWTPM_WONT_START}" ]; then
+				echo "Server did not open port ${SWTPM_CTRL_PORT}"
+				kill -9 "${SWTPM_PID}"
+				exit 1
+			fi
 		fi
 		return 0
 		;;
@@ -527,19 +549,24 @@ function run_swtpm()
 			--ctrl "type=unixio,path=${SWTPM_CTRL_UNIX_PATH}" &
 		rc=$?
 		if [ $rc -ne 0 ]; then
+			# Due to '&' above, an error means SWTPM_EXE is bad
 			echo "Could not run ${SWTPM_EXE} using ${iface}"
 			exit 1
 		fi
 		SWTPM_PID=$!
 		if wait_for_socketfile "${SWTPM_CMD_UNIX_PATH}" 2; then
-			echo "Server did not create UnixIO socket ${SWTPM_CMD_UNIX_PATH}"
-			kill -9 "${SWTPM_PID}"
-			exit 1
+			if [ -z "${SWTPM_RUN_SWTPM_WONT_START}" ]; then
+				echo "Server did not create UnixIO socket ${SWTPM_CMD_UNIX_PATH}"
+				kill -9 "${SWTPM_PID}"
+				exit 1
+			fi
 		fi
 		if wait_for_socketfile "${SWTPM_CTRL_UNIX_PATH}" 1; then
-			echo "Server did not create UnixIO socket ${SWTPM_CTRL_UNIX_PATH}"
-			kill -9 "${SWTPM_PID}"
-			exit 1
+			if [ -z "${SWTPM_RUN_SWTPM_WONT_START}" ]; then
+				echo "Server did not create UnixIO socket ${SWTPM_CTRL_UNIX_PATH}"
+				kill -9 "${SWTPM_PID}"
+				exit 1
+			fi
 		fi
 		return 0
 		;;
