tests: Check for permanent state file change due to TPM2_PCR_Read
Extend a test case to check whether the permanent state files changes
when a TPM2_PCR_Read() is executed. The state file change would cause
timeouts inside VMs when an fsync() is used that fully synchronzies the
state of the TPM 2 with the data on disk. The issue has been resolved in
more recent versions of libtpms (master and branches). The updated
libtpms is required if fsync() for files and directories is to be enabled.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

diff --git a/tests/_test_tpm2_savestate b/tests/_test_tpm2_savestate
--- a/tests/_test_tpm2_savestate
+++ b/tests/_test_tpm2_savestate
@@ -122,6 +122,10 @@ if [ "$RES" != "$exp" ]; then
 	exit 1
 fi
 
+# Wait 5 seconds to check whether the permanent state changes due to the PCR_Read
+sha1_permanent="$(get_sha1_file "${STATE_FILE}")"
+sleep 5
+
 swtpm_open_cmddev ${SWTPM_INTERFACE} 100
 # Read PCR 10
 #                                                   length         CC            count       hashalg         sz
@@ -131,6 +135,13 @@ if [ "$RES" != "$exp" ]; then
 	echo "Error: (2) Did not get expected result from TPM2_PCR_Read(10)"
 	echo "expected: $exp"
 	echo "received: $RES"
+	exit 1
+fi
+
+if [ "${sha1_permanent}" != "$(get_sha1_file "${STATE_FILE}")" ]; then
+	echo "Error: To avoid command timeouts, the permanent state ${STATE_FILE} must "
+	echo "       not change due short-running commands like TPM2_PCR_Read()."
+	echo "       You need a more recent version of libtpms."
 	exit 1
 fi
 
