tests: Get swtpm PID from shell and validate against pidfile after
Get the PID of the started swtpm from the shell and validate it
against the contents of the pidfile afterwards.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

diff --git a/tests/common b/tests/common
--- a/tests/common
+++ b/tests/common
@@ -718,3 +718,19 @@ function check_seccomp_profile()
 	fi
 	return 0
 }
+
+# Validate the content of the pid file
+# @1: Expected PID
+# @2: pid file filename
+function validate_pidfile()
+{
+	local pid="$1"
+	local pidfile="$2"
+
+	if [ "$PID" != "$(cat $PID_FILE)" ]; then
+		echo "Error: pid file contains unexpected PID value."
+		echo "expected: $pid"
+		echo "actual  : $(cat $pidfile)"
+		exit 1
+	fi
+}
