tests: Add test case for state migration and storage locking
Add a test case that monitors the locking of the storage by swtpm using the
directory storage backend to ensure that the lock is taken at the right
time and released when required.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

diff --git a/tests/common b/tests/common
--- a/tests/common
+++ b/tests/common
@@ -915,3 +915,63 @@ function skip_test_linked_with_asan()
 		fi
 	fi
 }
+
+# Have swtpm lock or re-lock the storage. Neither locking nor re-locking
+# may produce an error
+#
+# @param1: reason like 'lock' or 're-lock'
+function swtpm_lock_storage()
+{
+	local reason="$1"
+
+	if ! run_swtpm_ioctl  "${SWTPM_INTERFACE}" --lock-storage 0; then
+		echo "Error: 'swtpm_ioctl --lock-storage' to ${reason} storage failed"
+		exit 1
+	fi
+}
+
+# Check that swtpm has no lock on the directory backend storage
+function check_swtpm_no_storage_lock()
+{
+	local pid="$1"
+
+	if [ -d "/proc/${pid}/fd" ]; then
+		if [ -n "$(ls -l "/proc/${pid}/fd" | grep -E "\.lock\$")" ]; then
+			echo "Error: swtpm must not have storage locked"
+			ls -l /proc/${1}/fd
+			exit 1
+		fi
+	elif [ -n "$(type -P lsof)" ]; then
+		if [ -n "$(lsof -p "${pid}" | grep -e "\.lock\$")" ]; then
+			echo "Error: swtpm must not have storage locked"
+			lsof -p "${pid}"
+			exit 1
+		fi
+	else
+		echo "Missing procfs directory and lsof tool to determine open files."
+		exit 1
+	fi
+}
+
+# Check that swtpm has a lock on the directory backend storage
+function check_swtpm_storage_locked()
+{
+	local pid="$1"
+
+	if [ -d "/proc/${pid}/fd" ]; then
+		if [ -z "$(ls -l "/proc/${pid}/fd" | grep -E "\.lock\$")" ]; then
+			echo "Error: swtpm must have storage locked"
+			ls -l /proc/${1}/fd
+			exit 1
+		fi
+	elif [ -n "$(type -P lsof)" ]; then
+		if [ -z "$(lsof -p "${pid}" | grep -e "\.lock\$")" ]; then
+			echo "Error: swtpm must have storage locked"
+			ls -l /proc/${1}/fd
+			exit 1
+		fi
+	else
+		echo "Missing procfs directory and lsof tool to determine open files."
+		exit 1
+	fi
+}
