swtpm: Add command line parameter for pidfile
Add support for --pid file=<pidfile> command line parameter support.
The swtpm_cuse and swtpm now write their process IDs (pids) into
a file.

Signed-off-by: Stefan Berger <stefanb@linux.vnet.ibm.com>

diff --git a/tests/test_commandline b/tests/test_commandline
--- a/tests/test_commandline
+++ b/tests/test_commandline
@@ -8,6 +8,7 @@ SWTPM=swtpm
 SWTPM_EXE=$ROOT/src/swtpm/$SWTPM
 TPMDIR=`mktemp -d`
 TPMAUTHORING=$ROOT/src/swtpm_setup/swtpm_setup
+PID_FILE=$TPMDIR/${SWTPM}.pid
 PATH=${PWD}/${ROOT}/src/swtpm:$PATH
 PATH=${PWD}/${ROOT}/src/swtpm_setup:$PATH
 PATH=${PWD}/${ROOT}/src/swtpm_bios:$PATH
@@ -65,7 +66,7 @@ function wait_port_closed()
 
 # Test 1: test port and directory command line parameters
 
-$SWTPM_EXE socket -p $PORT -i $TPMDIR &>/dev/null &
+$SWTPM_EXE socket -p $PORT -i $TPMDIR --pid file=$PID_FILE &>/dev/null &
 PID=$!
 
 wait_port_open $PORT $PID
@@ -75,6 +76,18 @@ if [ $? -ne 0 ]; then
 	echo "Test 1 failed: TPM process not running"
 	exit 1
 fi
+
+if [ ! -r $PID_FILE ]; then
+	echo "Error: CUSE TPM did not write pidfile."
+	exit 1
+fi
+
+PIDF="$(cat $PID_FILE)"
+if [ "$PIDF" != "$PID" ]; then
+	echo "Error: CUSE TPM wrote pid $PIDF, but found $PID."
+	exit 1
+fi
+
 
 swtpm_bios &>/dev/null
 
diff --git a/tests/test_init b/tests/test_init
--- a/tests/test_init
+++ b/tests/test_init
@@ -17,6 +17,7 @@ VTPM_NAME="vtpm-test-init"
 export TPM_PATH=$(mktemp -d)
 STATE_FILE=$TPM_PATH/tpm-00.permall
 VOLATILE_STATE_FILE=$TPM_PATH/tpm-00.volatilestate
+PID_FILE=$TPM_PATH/${SWTPM}.pid
 
 function cleanup()
 {
@@ -36,7 +37,7 @@ fi
 
 rm -f $STATE_FILE $VOLATILE_STATE_FILE 2>/dev/null
 
-$SWTPM_EXE -n $VTPM_NAME
+$SWTPM_EXE --pid file=$PID_FILE -n $VTPM_NAME
 sleep 0.5
 PID=$(ps aux | grep $SWTPM | grep -E "$VTPM_NAME\$" | gawk '{print $2}')
 
@@ -45,6 +46,17 @@ ps aux | grep $SWTPM | grep -v grep
 kill -0 $PID
 if [ $? -ne 0 ]; then
 	echo "Error: CUSE TPM did not start."
+	exit 1
+fi
+
+if [ ! -r $PID_FILE ]; then
+	echo "Error: CUSE TPM did not write pidfile."
+	exit 1
+fi
+
+PIDF="$(cat $PID_FILE)"
+if [ "$PIDF" != "$PID" ]; then
+	echo "Error: CUSE TPM wrote pid $PIDF, but found $PID."
 	exit 1
 fi
 
