samples: Add support for password protected root CA priv. key
Support creation and usage of the root CA with a password protected
private key. The root CA's key password can be set using the environment
variable SWTPM_ROOTCA_PASSWORD.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

diff --git a/tests/test_swtpm_setup_create_cert b/tests/test_swtpm_setup_create_cert
--- a/tests/test_swtpm_setup_create_cert
+++ b/tests/test_swtpm_setup_create_cert
@@ -60,6 +60,9 @@ _EOF_
 # We need to adapt the PATH so the correct swtpm_cert is picked
 export PATH=${ROOT}/src/swtpm_cert:${PATH}
 
+# Create a ROOT CA with a password-protected private key
+export SWTPM_ROOTCA_PASSWORD=password
+
 # we need to create at least one cert: --create-ek-cert
 $SWTPM_SETUP \
 	--runas root \
@@ -95,6 +98,12 @@ if [ ! -r "${CERTSERIAL}" ]; then
 	echo "Error: Cert serial number file ${CERTSERIAL} was not created."
 	echo "Setup Logfile:"
 	cat ${workdir}/logfile
+	exit 1
+fi
+
+if [ -z "$(grep "ENCRYPTED PRIVATE KEY" ${workdir}/swtpm-localca-rootca-privkey.pem)" ]; then
+	echo "Error: Root CA's private key should be encrypted"
+	cat ${workdir}/swtpm-localca-rootca-privkey.pem
 	exit 1
 fi
 
