tests: replace plain sleep with wait for PID file to be gone
Replace the short sleeps with waits for the PID file to be gone.

Signed-off-by: Stefan Berger <stefanb@linux.vnet.ibm.com>

diff --git a/tests/test_vtpm_proxy b/tests/test_vtpm_proxy
--- a/tests/test_vtpm_proxy
+++ b/tests/test_vtpm_proxy
@@ -107,15 +107,14 @@ if [ "$res" != "$exp" ]; then
 	exit 1
 fi
 
-sleep 0.2
-kill -0 $PID 2>/dev/null
-if [ $? -eq 0 ]; then
-	echo "Error: TPM should not be running anymore."
+if wait_file_gone $PID_FILE 2; then
+	echo "Error: TPM should have removed PID file by now."
 	exit 1
 fi
 
-if [ -f $PID_FILE ]; then
-	echo "Error: TPM should have removed the PID file."
+kill -0 $PID 2>/dev/null
+if [ $? -eq 0 ]; then
+	echo "Error: TPM should not be running anymore."
 	exit 1
 fi
 
