swtpm: Implement two more control channel commands.
Implement two more control channel commands:
- CMD_STORE_VOLATILE
- CMD_HASH_DATA

Implement test cases.

Signed-off-by: Stefan Berger <stefanb@linux.vnet.ibm.com>

diff --git a/tests/test_ctrlchannel b/tests/test_ctrlchannel
--- a/tests/test_ctrlchannel
+++ b/tests/test_ctrlchannel
@@ -43,7 +43,7 @@ socat -x -t10 FILE:$CMD_PATH,rdonly UNIX-CLIENT:$SOCK_PATH 2>&1 | \
 	sed -n '/^ /p' | \
 	tail -n1 > $RESP_PATH
 res="$(cat $RESP_PATH)"
-exp=" 00 00 00 00 00 00 04 b7"
+exp=" 00 00 00 00 00 00 04 f7"
 if [ "$res" != "$exp" ]; then
 	echo "Error: Unexpected response from CMD_GET_CAPABILITY:"
 	echo "       actual  : $res"
@@ -76,6 +76,25 @@ if [ "$res" != "$exp" ]; then
 	echo "Error: Unexpected response from sending unsupported command:"
 	echo "       actual  : $res"
 	echo "       expected: $exp"
+	exit 1
+fi
+
+# Save the volatile state: CMD_STORE_VOLATILE = 0x00 00 00 0a
+/bin/echo -en '\x00\x00\x00\x0a' >$CMD_PATH
+socat -x -t10 FILE:$CMD_PATH,rdonly UNIX-CLIENT:$SOCK_PATH 2>&1 | \
+	sed -n '/^ /p' | \
+	tail -n1 > $RESP_PATH
+res="$(cat $RESP_PATH)"
+exp=" 00 00 00 00"
+if [ "$res" != "$exp" ]; then
+	echo "Error: Unexpected response from CMD_STORE_VOLATILE:"
+	echo "       actual  : $res"
+	echo "       expected: $exp"
+	exit 1
+fi
+
+if [ ! -r $TPMDIR/tpm-00.volatilestate ]; then
+	echo "Error: Socket TPM: Did not write volatile state file"
 	exit 1
 fi
 
@@ -161,7 +180,7 @@ socat -x -t10 FILE:$CMD_PATH,rdonly UNIX-CLIENT:$SOCK_PATH 2>&1 | \
 	sed -n '/^ /p' | \
 	tail -n1 > $RESP_PATH
 res="$(cat $RESP_PATH)"
-exp=" 00 00 00 00 00 00 04 b7"
+exp=" 00 00 00 00 00 00 04 f7"
 if [ "$res" != "$exp" ]; then
 	echo "Error: Socket TPM: Unexpected response from CMD_GET_CAPABILITY:"
 	echo "       actual  : $res"
@@ -209,6 +228,25 @@ if [ "$RES" != "$exp" ]; then
 	exit 1
 fi
 
+# Save the volatile state: CMD_STORE_VOLATILE = 0x00 00 00 0a
+/bin/echo -en '\x00\x00\x00\x0a' >$CMD_PATH
+socat -x -t10 FILE:$CMD_PATH,rdonly UNIX-CLIENT:$SOCK_PATH 2>&1 | \
+	sed -n '/^ /p' | \
+	tail -n1 > $RESP_PATH
+res="$(cat $RESP_PATH)"
+exp=" 00 00 00 00"
+if [ "$res" != "$exp" ]; then
+	echo "Error: Socket TPM: Unexpected response from CMD_STORE_VOLATILE:"
+	echo "       actual  : $res"
+	echo "       expected: $exp"
+	exit 1
+fi
+
+if [ ! -r $TPMDIR/tpm-00.volatilestate ]; then
+	echo "Error: Socket TPM: Did not write volatile state file"
+	exit 1
+fi
+
 # 1. Send command to get TPM established flag: CMD_GET_TPMESTABLISHED = 00 00 00 04
 echo -en '\x00\x00\x00\x04' > $CMD_PATH
 cat $RESP_PATH
@@ -226,7 +264,6 @@ fi
 
 # 2. Send command to start HASH : CMD_HASH_START = 00 00 00 06
 echo -en '\x00\x00\x00\x06' > $CMD_PATH
-cat $RESP_PATH
 socat -x -t10 FILE:$CMD_PATH,rdonly UNIX-CONNECT:$SOCK_PATH 2>&1 | \
 	sed -n '/^ /p' | \
 	tail -n1 > $RESP_PATH
@@ -234,6 +271,22 @@ res="$(cat $RESP_PATH)"
 exp=" 00 00 00 00"
 if [ "$res" != "$exp" ]; then
 	echo "Error: Socket TPM: Unexpected response from sending CMD_HASH_START command:"
+	echo "       actual  : $res"
+	echo "       expected: $exp"
+	exit 1
+fi
+
+# 2.1. Send command to hash data : CMD_HASH_DATA = 00 00 00 07 uint32(length) data
+# We send 0x100 null bytes
+echo -en '\x00\x00\x00\x07\x00\x00\x20\x00' > $CMD_PATH
+dd if=/dev/zero count=$((0x2000)) bs=1 >> $CMD_PATH 2>/dev/null
+socat -x -t10 FILE:$CMD_PATH,rdonly UNIX-CONNECT:$SOCK_PATH 2>&1 | \
+	sed -n '/^ /p' | \
+	tail -n1 > $RESP_PATH
+res="$(cat $RESP_PATH)"
+exp=" 00 00 00 00"
+if [ "$res" != "$exp" ]; then
+	echo "Error: Socket TPM: Unexpected response from sending CMD_HASH_DATA command:"
 	echo "       actual  : $res"
 	echo "       expected: $exp"
 	exit 1
@@ -303,7 +356,7 @@ fi
 exec 100<>/dev/tcp/localhost/65530
 echo -en '\x00\xC1\x00\x00\x00\x0E\x00\x00\x00\x15\x00\x00\x00\x11' >&100
 RES=$(cat <&100 | od -t x1 -A n | tr -d "\n")
-exp=' 00 c4 00 00 00 1e 00 00 00 00 31 a2 dc 4c 22 f9 c5 44 4a 41 62 5d 05 f9 58 98 e0 55 f7 50'
+exp=' 00 c4 00 00 00 1e 00 00 00 00 c4 e1 e1 c9 81 c0 cd b1 e0 43 df 97 20 72 f9 5d a9 ff 06 ff'
 if [ "$RES" != "$exp" ]; then
 	echo "Error: (1) Did not get expected result from TPM_PCRRead(17)"
 	echo "expected: $exp"
