test: Add test case for creating a certificate for an ML-DSA-65 EK
Test creating an EK certificate with a pre-created public ML-DSA-65 key
and test for expected size of the certificate file.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

diff --git a/tests/test_tpm2_swtpm_cert b/tests/test_tpm2_swtpm_cert
--- a/tests/test_tpm2_swtpm_cert
+++ b/tests/test_tpm2_swtpm_cert
@@ -121,6 +121,30 @@ echo -n > "${cert}"
 echo "Test 4: OK"
 
 
+if ! ${SWTPM_CERT} \
+       --tpm2 \
+       --signkey "${TESTDIR}/data/signkey.pem" \
+       --issuercert "${TESTDIR}/data/issuercert.pem" \
+       --out-cert "${cert}" \
+       --pubkey "${TESTDIR}/data/mldsa65pubek.pem" \
+       --days 3650 \
+       --subject "OU=test,L=NewYork,ST=NY,C=US" \
+       --pem \
+       --tpm-manufacturer IBM --tpm-model swtpm-libtpms --tpm-version 1.2 \
+       --tpm-spec-family 2.0 --tpm-spec-revision 146 --tpm-spec-level 0; then
+       echo "Error: ${SWTPM_CERT} returned error code."
+       exit 1
+fi
+
+#expecting size to be constant
+check_cert_size "${cert}" 3747
+
+# truncate result file
+#certtool --certificate-info --infile ${cert}
+echo -n > "${cert}"
+echo "Test 5: OK"
+
+
 ###################### Platform Certificate #####################
 
 if ! ${SWTPM_CERT} \
@@ -146,7 +170,7 @@ check_cert_size "${cert}" 1484
 
 # truncate result file
 echo -n > "${cert}"
-echo "Test 5: OK"
+echo "Test 6: OK"
 
 ###################### IAK Certificate #####################
 
@@ -188,7 +212,7 @@ check_cert_size "${cert}" 1375
 
 # truncate result file
 echo -n > "${cert}"
-echo "Test 6: OK"
+echo "Test 7: OK"
 
 ###################### IDevID Certificate #####################
 
@@ -230,7 +254,7 @@ check_cert_size "${cert}" 1375
 
 # truncate result file
 echo -n > "${cert}"
-echo "Test 7: OK"
+echo "Test 8: OK"
 
 ####################### max. serial number #####################
 
@@ -281,4 +305,4 @@ fi
 
 # truncate result file
 echo -n > "${cert}"
-echo "Test 8: OK"
+echo "Test 9: OK"
