tests: Derive support for CUSE from SWTPM_EXE help screen
Use 'swtpm --help | grep cuse' to determine whether CUSE interface
is supported and CUSE related tests need to run. Make sure that
SWTPM_EXE is available when test_cuse is sourced.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

diff --git a/tests/test_cuse b/tests/test_cuse
--- a/tests/test_cuse
+++ b/tests/test_cuse
@@ -13,8 +13,12 @@ if [ "$(id -u)" -ne 0 ]; then
 	exit 77
 fi
 
-if ! grep -q -E '#[[:blank:]]*define[[:blank:]]+WITH_CUSE[[:blank:]]+1[[:blank:]]*$' \
-		"${PWD}/../config.h"; then
+if [ -z "${SWTPM_EXE}" ]; then
+	echo "Error: SWTPM_EXE must be set"
+	exit 1
+fi
+
+if ! ${SWTPM_EXE} --help | grep -q cuse; then
 	echo "Skipping test: swtpm was not compiled with CUSE interface"
 	exit 77
 fi
