swtpm_localca: Created certificates for CAs and TPM that do not expire
Rather than having the CA certificates, that are created on the fly,
expire in 10 years, have them not expire at all.

Also create TPM certificates that don't expire and extend a test
case for this.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

diff --git a/tests/test_swtpm_setup_create_cert b/tests/test_swtpm_setup_create_cert
--- a/tests/test_swtpm_setup_create_cert
+++ b/tests/test_swtpm_setup_create_cert
@@ -114,6 +114,15 @@ if [ -z "$($CERTTOOL --inder --infile "${certfile}" -i | grep "2048 bits")" ]; t
 	exit 1
 fi
 
+expiration="$($CERTTOOL --inder --infile "${certfile}" -i | grep "Not After:")"
+expected="Not After: Fri Dec 31 23:59:59 UTC 9999"
+if [ -z "$(echo "${expiration}" | grep "${expected}")" ]; then
+	echo "Error: EK file '${certfile}' does not expire in 9999"
+	echo "actual:   ${expiration}"
+	echo "expected: ${expected}"
+	exit 1
+fi
+
 echo "OK"
 
 exit 0
