tests: Wait for chardev to appear
Wait for the chardev the VTPM proxy device creates to actually appear.
In some cases the exec statement opening the file would otherwise
create a file /dev/tpm0 for example and subsequently tests then ended
up failing.

Signed-off-by: Stefan Berger <stefanb@linux.vnet.ibm.com>

diff --git a/tests/test_vtpm_proxy b/tests/test_vtpm_proxy
--- a/tests/test_vtpm_proxy
+++ b/tests/test_vtpm_proxy
@@ -51,6 +51,16 @@ fi
 TPM_DEVICE=$(sed -n 's,.*\(/dev/tpm[0-9]\+\).*,\1,p' $LOGFILE)
 echo "Using ${TPM_DEVICE}."
 
+# Wait for chardev to appear
+for ((i = 0; i < 10; i ++)); do
+	[ -c "${TPM_DEVICE}" ] && break
+	sleep 0.1
+done
+if ! [ -c "${TPM_DEVICE}" ]; then
+	echo "Error: Chardev ${TPM_DEVICE} did not appear"
+	exit 1
+fi
+
 # Open access to the TPM
 exec 100<>$TPM_DEVICE
 if [ $? -ne 0 ]; then
