tests: Extends test_volatilestate with checks on establishment bit
Extend the testcase test_volatilestate with check on the TPM
establishment bit and that it is saved across volatile save/load
operations.

diff --git a/tests/test_volatilestate b/tests/test_volatilestate
--- a/tests/test_volatilestate
+++ b/tests/test_volatilestate
@@ -89,6 +89,16 @@ if [ "$RES" != "$exp" ]; then
 	exit 1
 fi
 
+# Check the TPM Established bit after the hashing
+RES=$($CUSE_TPM_IOCTL -e /dev/$VTPM_NAME)
+exp='tpmEstablished is 1'
+if [ "$RES" != "$exp" ]; then
+	echo "Error (2): TPM Established flag has wrong value."
+	echo "expected: $exp"
+	echo "received: $RES"
+	exit 1
+fi
+
 # Save the volatile state
 $CUSE_TPM_IOCTL -v /dev/$VTPM_NAME
 
@@ -135,6 +145,16 @@ if [ "$RES" != "$exp" ]; then
 	exit 1
 fi
 
+# Check that the TPM Established bit is still set
+RES=$($CUSE_TPM_IOCTL -e /dev/$VTPM_NAME)
+exp='tpmEstablished is 1'
+if [ "$RES" != "$exp" ]; then
+	echo "Error (2): TPM Established flag has wrong value."
+	echo "expected: $exp"
+	echo "received: $RES"
+	exit 1
+fi
+
 # Save the volatile state again
 $CUSE_TPM_IOCTL -v /dev/$VTPM_NAME
 
@@ -164,6 +184,15 @@ if [ "$RES" != "$exp" ]; then
 	exit 1
 fi
 
+# Check that the TPM Established bit is still set
+RES=$($CUSE_TPM_IOCTL -e /dev/$VTPM_NAME)
+exp='tpmEstablished is 1'
+if [ "$RES" != "$exp" ]; then
+	echo "Error (2): TPM Established flag has wrong value."
+	echo "expected: $exp"
+	echo "received: $RES"
+	exit 1
+fi
 
 # Finale shut down
 exec 100>&-
