tests: Extend existing test with one for rejection of locality 4
Signed-off-by: Stefan Berger <stefanb@linux.vnet.ibm.com>

diff --git a/tests/test_locality b/tests/test_locality
--- a/tests/test_locality
+++ b/tests/test_locality
@@ -131,4 +131,66 @@ fi
 
 echo "OK"
 
+
+$SWTPM_EXE --locality reject-locality-4 -n $VTPM_NAME
+sleep 0.5
+PID=$(ps aux | grep $SWTPM | grep -E "$VTPM_NAME\$" | gawk '{print $2}')
+
+ps aux | grep $SWTPM | grep -v grep
+
+kill -0 $PID
+if [ $? -ne 0 ]; then
+	echo "Error: CUSE TPM did not start."
+	exit 1
+fi
+
+# Init the TPM
+$CUSE_TPM_IOCTL -i /dev/$VTPM_NAME
+if [ $? -ne 0 ]; then
+	echo "Error: Could not initialize the CUSE TPM."
+	exit 1
+fi
+
+kill -0 $PID 2>/dev/null
+if [ $? -ne 0 ]; then
+	echo "Error: CUSE TPM not running anymore after INIT."
+	exit 1
+fi
+
+# Set locality 4 on the TPM -- this must fail now
+$CUSE_TPM_IOCTL -l 4 /dev/$VTPM_NAME
+if [ $? -eq 0 ]; then
+	echo "Error: CUSE TPM MUST NOT accept locality 4."
+	exit 1
+fi
+
+# Set illegal locality 5 on the TPM
+$CUSE_TPM_IOCTL -l 5 /dev/$VTPM_NAME
+if [ $? -eq 0 ]; then
+	echo "Error: CUSE TPM accepted locality 5."
+	exit 1
+fi
+
+# Shut down TPM
+$CUSE_TPM_IOCTL -s /dev/$VTPM_NAME
+if [ $? -ne 0 ]; then
+	echo "Error: Could not shut down the CUSE TPM."
+	exit 1
+fi
+sleep 0.5
+
+kill -0 $PID 2>/dev/null
+if [ $? -eq 0 ]; then
+	echo "Error: CUSE TPM should not be running anymore."
+	exit 1
+fi
+
+if [ ! -e $STATE_FILE ]; then
+	echo "Error: TPM state file $STATE_FILE does not exist."
+	exit 1
+fi
+
+echo "OK"
+
+
 exit 0
