tests: Add test cases for swtpm_cert with max serial number
Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

diff --git a/tests/test_tpm2_swtpm_cert b/tests/test_tpm2_swtpm_cert
--- a/tests/test_tpm2_swtpm_cert
+++ b/tests/test_tpm2_swtpm_cert
@@ -130,3 +130,54 @@ check_cert_size "${cert}" 1411
 #certtool --certificate-info --infile ${cert}
 echo -n > "${cert}"
 echo "Test 4: OK"
+
+
+####################### max. serial number #####################
+
+# max. serial number -- must pass
+if ! ${SWTPM_CERT} \
+	--tpm2 \
+	--signkey "${TESTDIR}/data/signkey.pem" \
+	--issuercert "${TESTDIR}/data/issuercert.pem" \
+	--out-cert "${cert}" \
+	--pubkey "${TESTDIR}/data/pubek.pem" \
+	--days 3650 \
+	--subject "OU=foo,L=NewYork,ST=NY,C=US" \
+	--pem \
+	--serial 1461501637330902918203684832716283019655932542975 \
+	--tpm-manufacturer IBM --tpm-model swtpm-libtpms --tpm-version 1.2 \
+	--tpm-spec-family 2.0 --tpm-spec-revision 146 --tpm-spec-level 0; then
+	echo "Error: ${SWTPM_CERT} failed with max. serial number."
+	exit 1
+fi
+tmp=$(certtool --certificate-info --infile "${cert}" |
+      sed -n 's/.*Serial Number.*: \([[:xdigit:]*]\)/\1/p')
+exp="00ffffffffffffffffffffffffffffffffffffffff"
+if [ "${tmp}" != "${exp}" ]; then
+	echo "Error: unexpected serial number in cert"
+	echo "expected: ${exp}"
+	echo "actual  : ${tmp}"
+	exit 1
+fi
+
+# max. serial number + 1 -- must fail
+if ${SWTPM_CERT} \
+	--tpm2 \
+	--signkey "${TESTDIR}/data/signkey.pem" \
+	--issuercert "${TESTDIR}/data/issuercert.pem" \
+	--out-cert "${cert}" \
+	--pubkey "${TESTDIR}/data/pubek.pem" \
+	--days 3650 \
+	--subject "OU=foo,L=NewYork,ST=NY,C=US" \
+	--pem \
+	--serial 1461501637330902918203684832716283019655932542976 \
+	--tpm-manufacturer IBM --tpm-model swtpm-libtpms --tpm-version 1.2 \
+	--tpm-spec-family 2.0 --tpm-spec-revision 146 --tpm-spec-level 0; then
+	echo "Error: ${SWTPM_CERT} should have failed with max. serial number + 1."
+	exit 1
+fi
+
+# truncate result file
+#certtool --certificate-info --infile ${cert}
+echo -n > "${cert}"
+echo "Test 5: OK"
diff --git a/tests/test_tpm2_swtpm_setup_create_cert b/tests/test_tpm2_swtpm_setup_create_cert
--- a/tests/test_tpm2_swtpm_setup_create_cert
+++ b/tests/test_tpm2_swtpm_setup_create_cert
@@ -39,6 +39,9 @@ issuercert = ${ISSUERCERT}
 certserial = ${CERTSERIAL}
 _EOF_
 
+#max. serial number must immediately be replace with 20 digits one
+echo -n 1461501637330902918203684832716283019655932542975 > "${CERTSERIAL}"
+
 cat <<_EOF_ > "${workdir}/swtpm-localca.options"
 --tpm-manufacturer IBM
 --tpm-model swtpm-libtpms
@@ -102,6 +105,12 @@ for keysize in ${keysizes}; do
 
 	if [ ! -r "${CERTSERIAL}" ]; then
 		echo "Error: Cert serial number file ${CERTSERIAL} was not created."
+		exit 1
+	fi
+
+	tmp=$(cat "${CERTSERIAL}")
+	if [ "${#tmp}" -ne 20 ]; then
+		echo "Error: Cert serial number in file should now be 20 digits long."
 		exit 1
 	fi
 
