tests: Use SOCK_STREAM for CMD_SET_DATAFD socketpair
Switch to SOCK_STREAM for the CMD_SET_DATAFD socketpair where the one
end is passed to swtpm to test that this type of socket will cause
automatic termination of swtpm when the connection is lost. This is also
the socket type that QEMU uses.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

diff --git a/tests/test_ctrlchannel3 b/tests/test_ctrlchannel3
--- a/tests/test_ctrlchannel3
+++ b/tests/test_ctrlchannel3
@@ -55,6 +55,11 @@ if [ $res -ne 0 ]; then
 	exit 1
 fi
 
+if wait_process_gone ${PID} 4; then
+	echo "Error: TPM should not be running anymore."
+	exit 1
+fi
+
 echo "OK"
 
 exit 0
