swtpm_setup: Propagate --allow-signing option for certificate creation
Propagate the --allow-signing option from swtpm_setup into swtpm_localca
so that a certificate will finally be created that reflects the 'Digital
Signature' key usage.

Extend a test case to check for the 'Digitial signature' flag under
'key usage' when --allow-signing is passed.

Resolves: https://github.com/stefanberger/swtpm/issues/1061
Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

diff --git a/tests/test_tpm2_swtpm_setup_create_cert b/tests/test_tpm2_swtpm_setup_create_cert
--- a/tests/test_tpm2_swtpm_setup_create_cert
+++ b/tests/test_tpm2_swtpm_setup_create_cert
@@ -137,6 +137,12 @@ for keysize in ${keysizes}; do
 		$CERTTOOL --inder --infile "${certfile}" -i
 		exit 1
 	fi
+	if ! $CERTTOOL --inder --infile "${certfile}" -i | grep "Key Usage" -A1 | \
+		grep -q "Digital signature."; then
+		echo "Error: EK file '${certfile}' does not have key usage flag 'Digitial signature' set."
+		$CERTTOOL --inder --infile "${certfile}" -i
+		exit 1
+	fi
 
 	rm -rf "${SIGNINGKEY}" "${ISSUERCERT}" "${CERTSERIAL}" "${USER_CERTSDIR}"/ek-*.crt
 done
