swtpm: Fix --print-capabilities for 'swtpm chardev'
This patch fixes the following issue:

$ ./src/swtpm/swtpm chardev --print-capabilities --tpm2
swtpm: Error: Missing character device or file descriptor

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

diff --git a/tests/test_tpm2_ctrlchannel2 b/tests/test_tpm2_ctrlchannel2
--- a/tests/test_tpm2_ctrlchannel2
+++ b/tests/test_tpm2_ctrlchannel2
@@ -35,6 +35,14 @@ if [ $(id -u) -eq 0 ]; then
 	FILEOWNER="$(id -u nobody) $(id -G nobody | cut -d" " -f1)"
 fi
 
+# make sure --print-capabiities exits with '0'
+msg=$($SWTPM_EXE chardev --print-capabilities 2>&1)
+if [ $? -ne 0 ]; then
+	echo "Error: swtpm chardev --print-capabilities failed"
+	echo "$msg"
+	exit 1
+fi
+
 FILEMODE=621
 # use a pseudo terminal
 exec 100<>/dev/ptmx
