tests: Fix code to pass shellcheck with some errors disabled
Fix the test cases to pass shellcheck with some of the errors
disable.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

diff --git a/tests/test_tpm2_save_load_state_2 b/tests/test_tpm2_save_load_state_2
--- a/tests/test_tpm2_save_load_state_2
+++ b/tests/test_tpm2_save_load_state_2
@@ -3,7 +3,7 @@
 # For the license, see the LICENSE file in the root directory.
 #set -x
 
-if [ ${SWTPM_TEST_IBMTSS2:-0} -eq 0 ]; then
+if [ "${SWTPM_TEST_IBMTSS2:-0}" -eq 0 ]; then
 	echo "SWTPM_TEST_IBMTSS2 must be set to run this test."
 	exit 77
 fi
@@ -17,7 +17,7 @@ if [ $? -ne 0 ]; then
 	echo "Could not find TPM2 tools (e.g., (tss)startup, (tss)nvdefinespace) in PATH."
 	exit 77
 fi
-TOOLSPATH=$(dirname $(type -P ${PREFIX}startup))
+TOOLSPATH=$(dirname "$(type -P "${PREFIX}startup")")
 
 ROOT=${abs_top_builddir:-$(dirname "$0")/..}
 TESTDIR=${abs_top_testdir:-$(dirname "$0")}
@@ -28,8 +28,6 @@ SWTPM_IOCTL=$ROOT/src/swtpm_ioctl/swtpm_ioctl
 TPMDIR="$(mktemp -d)" || exit 1
 PID_FILE=$TPMDIR/${SWTPM}.pid
 SOCK_PATH=$TPMDIR/sock
-CMD_PATH=$TPMDIR/cmd
-RESP_PATH=$TPMDIR/resp
 LOGFILE=$TPMDIR/logfile
 TMPFILE=$TPMDIR/tmpfile
 BINFILE=$TPMDIR/binfile
@@ -37,13 +35,13 @@ SIGFILE=$TPMDIR/sigfile
 STATEFILE=${STATEFILE:-$TPMDIR/state}
 
 STORE_PARAM="dir=$TPMDIR"
-if [ ${SWTPM_TEST_LINEAR_FILE:-0} -ne 0 ]; then
+if [ "${SWTPM_TEST_LINEAR_FILE:-0}" -ne 0 ]; then
 	echo "Testing with linear file backend ($STATEFILE)"
 	STORE_PARAM="backend-uri=file://$STATEFILE"
 fi
 
-source ${TESTDIR}/test_common
-source ${TESTDIR}/common
+source "${TESTDIR}/test_common"
+source "${TESTDIR}/common"
 skip_test_no_tpm20 "${SWTPM_EXE}"
 
 
@@ -51,11 +49,11 @@ trap "cleanup" SIGTERM EXIT
 
 function cleanup()
 {
-	rm -rf $TPMDIR
+	rm -rf "$TPMDIR"
 	# remove files from tss tools
 	rm -f h01*.bin nvp*.bin
 	if [ -n "$PID" ]; then
-		kill_quiet -SIGTERM $PID 2>/dev/null
+		kill_quiet -SIGTERM "$PID" 2>/dev/null
 	fi
 }
 
@@ -71,31 +69,31 @@ function fillup_nvram()
 
 	local i sz
 
-	if [ $create -eq 1 ]; then
+	if [ "$create" -eq 1 ]; then
 		# Fill up the NVRAM space with RSA 2048 keys;
 		# exactly 65 have to fit
-		${TOOLSPATH}/${PREFIX}createprimary -hi o -si > $TMPFILE
+		"${TOOLSPATH}/${PREFIX}createprimary" -hi o -si > "$TMPFILE"
 		if [ $? -ne 0 ]; then
 			echo "Error: createprimary failed."
 			exit 1
 		fi
-		if [ -z "$(grep 80000000 $TMPFILE)" ]; then
+		if [ -z "$(grep 80000000 "$TMPFILE")" ]; then
 			echo "Error: createprimary did not result in expected handle 80000000"
 			exit 1
 		fi
 		for ((i = 0x81000000; i < 0x81000100; i++)); do
-			${TOOLSPATH}/${PREFIX}evictcontrol \
+			"${TOOLSPATH}/${PREFIX}evictcontrol" \
 				-hi o \
 				-ho 80000000 \
-				-hp $(printf "%x" $i) &>$TMPFILE || break
+				-hp "$(printf "%x" "$i")" &>"$TMPFILE" || break
 		done
-		${TOOLSPATH}/${PREFIX}getcapability -cap 1 -pr 81000000 -pc 80 > $TMPFILE
+		"${TOOLSPATH}/${PREFIX}getcapability" -cap 1 -pr 81000000 -pc 80 > "$TMPFILE"
 		# We need know we need to see '65 Handles' for state created with
 		# libtpms-0.6.0 and 128kb NVRAM size
-		grep -i "65 Handles" $TMPFILE
+		grep -i "65 Handles" "$TMPFILE"
 		if [ $? -ne 0 ]; then
 			echo "Error: Did not find '65 Handles' keyword in output"
-			cat $TMPFILE
+			cat "$TMPFILE"
 			exit 1
 		fi
 
@@ -103,26 +101,26 @@ function fillup_nvram()
 		# we now have to find;
 		# for reference: libtpms v0.6.0 allowed 236 bytes
 		for ((sz = 0; ; sz++)); do
-			${TOOLSPATH}/${PREFIX}nvdefinespace \
+			"${TOOLSPATH}/${PREFIX}nvdefinespace" \
 				-hi o \
 				-ha 01000000 \
-				-sz ${sz} > ${TMPFILE} || break
+				-sz "${sz}" > "${TMPFILE}" || break
 			# this worked, so lets remove it and try the next size
 			#echo "NVRAM space of size $sz could be created"
-			${TOOLSPATH}/${PREFIX}nvundefinespace \
+			"${TOOLSPATH}/${PREFIX}nvundefinespace" \
 				-hi o \
-				-ha 01000000 > ${TMPFILE}
+				-ha 01000000 > "${TMPFILE}"
 		done
-		if [ $sz -gt 0 ]; then
+		if [ "$sz" -gt 0 ]; then
 			sz=$((sz - 1))
 			echo "Creating final space of size ${sz}"
-			${TOOLSPATH}/${PREFIX}nvdefinespace \
+			"${TOOLSPATH}/${PREFIX}nvdefinespace" \
 				-hi o \
 				-ha 01000000 \
-				-sz ${sz} > ${TMPFILE}
+				-sz ${sz} > "${TMPFILE}"
 			if [ $? -ne 0 ]; then
 				echo "Error: Could not create final NVRAM space."
-				cat ${TMPFILE}
+				cat "${TMPFILE}"
 				exit 1
 			fi
 		fi
@@ -139,38 +137,38 @@ function fillup_nvram()
 			echo "The NVRAM index is exactly of the right size (236 bytes)."
 		fi
 
-		echo -n "123" > $BINFILE
-		${TOOLSPATH}/${PREFIX}sign \
+		echo -n "123" > "$BINFILE"
+		"${TOOLSPATH}/${PREFIX}sign" \
 			-hk 81000000 \
-			-if ${BINFILE} \
-			-os ${SIGFILE} > $TMPFILE
+			-if "${BINFILE}" \
+			-os "${SIGFILE}" > "$TMPFILE"
 		if [ $? -ne 0 ]; then
 			echo "Error: Could not create signature."
-			cat $TMPFILE
+			cat "$TMPFILE"
 			exit 1
 		fi
 	fi
 
-	if [ $check -eq 1 ]; then
-		${TOOLSPATH}/${PREFIX}getcapability -cap 1 -pr 81000000 -pc 80 > $TMPFILE
+	if [ "$check" -eq 1 ]; then
+		"${TOOLSPATH}/${PREFIX}getcapability" -cap 1 -pr 81000000 -pc 80 > "$TMPFILE"
 		# We need know we need to see '65 Handles' for state created with
 		# libtpms-0.6.0 and 128kb NVRAM size
-		grep -i "65 Handles" $TMPFILE
+		grep -i "65 Handles" "$TMPFILE"
 		if [ $? -ne 0 ]; then
 			echo "Error: Did not find '65 Handles' keyword in output"
-			cat $TMPFILE
+			cat "$TMPFILE"
 			exit 1
 		fi
 
 		printf "Verifying signature with all the persisted keys\n"
-		echo -n "123" > $BINFILE
+		echo -n "123" > "$BINFILE"
 		for ((i = 0x81000000; i < 0x81000040; i++)); do
-			${TOOLSPATH}/${PREFIX}verifysignature \
-				-hk $(printf "%x" $i) \
-				-is ${SIGFILE} \
-				-if ${BINFILE} > $TMPFILE
+			"${TOOLSPATH}/${PREFIX}verifysignature" \
+				-hk "$(printf "%x" "$i")" \
+				-is "${SIGFILE}" \
+				-if "${BINFILE}" > "$TMPFILE"
 			if [ $? -ne 0 ]; then
-				echo "Verifying signature failed for handle $(printf "%x" $i)."
+				echo "Verifying signature failed for handle $(printf "%x" "$i")."
 				exit 1
 			fi
 		done
@@ -185,29 +183,29 @@ export TPM_DATA_DIR=$TPMDIR
 export TPM_SESSION_ENCKEY="807e2bfe898ddaed8fa6310e716a24dc" # for sessions
 
 $SWTPM_EXE socket \
-	--server port=${TPM_COMMAND_PORT} \
-	--tpmstate $STORE_PARAM \
-	--pid file=$PID_FILE \
-	--ctrl type=unixio,path=$SOCK_PATH \
-	--log file=$LOGFILE,level=20 \
+	--server "port=${TPM_COMMAND_PORT}" \
+	--tpmstate "$STORE_PARAM" \
+	--pid "file=$PID_FILE" \
+	--ctrl "type=unixio,path=$SOCK_PATH" \
+	--log "file=$LOGFILE,level=20" \
 	--tpm2 \
-	${SWTPM_TEST_SECCOMP_OPT} &
+	${SWTPM_TEST_SECCOMP_OPT:+${SWTPM_TEST_SECCOMP_OPT}} &
 
-if wait_for_file $PID_FILE 3; then
+if wait_for_file "$PID_FILE" 3; then
 	echo "Error: (1) Socket TPM did not write pidfile."
 	exit 1
 fi
 
-PID="$(cat $PID_FILE)"
+PID="$(cat "$PID_FILE")"
 
 # Send TPM_Init
-act=$($SWTPM_IOCTL --unix $SOCK_PATH -i 2>&1)
+act=$($SWTPM_IOCTL --unix "$SOCK_PATH" -i 2>&1)
 if [ $? -ne 0 ]; then
 	echo "Error: $SWTPM_IOCTL CMD_INIT failed: $act"
 	exit 1
 fi
 
-${TOOLSPATH}/${PREFIX}startup -c
+"${TOOLSPATH}/${PREFIX}startup" -c
 if [ $? -ne 0 ]; then
 	echo "Error: tpm_startup clear failed."
 	exit 1
@@ -216,18 +214,18 @@ fi
 fillup_nvram 1 1
 
 # Send Shutdown
-act=$($SWTPM_IOCTL --unix $SOCK_PATH -s 2>&1)
+act=$($SWTPM_IOCTL --unix "$SOCK_PATH" -s 2>&1)
 if [ $? -ne 0 ]; then
 	echo "Error: $SWTPM_IOCTL CMD_SHUTDOWN failed: $act"
 	exit 1
 fi
 
-if wait_process_gone ${PID} 4; then
+if wait_process_gone "${PID}" 4; then
 	echo "Error: swtpm did not shut down"
 	exit 1
 fi
 
-echo "============================" >> $LOGFILE
+echo "============================" >> "$LOGFILE"
 
 echo "TPM was shut down"
 
@@ -239,113 +237,113 @@ echo "TPM was shut down"
 # Run TPM2 with the created state and verify it's the same
 
 $SWTPM_EXE socket \
-	--server port=${TPM_COMMAND_PORT} \
-	--tpmstate $STORE_PARAM \
-	--pid file=$PID_FILE \
-	--ctrl type=unixio,path=$SOCK_PATH \
-	--log file=$LOGFILE,level=20 \
+	--server "port=${TPM_COMMAND_PORT}" \
+	--tpmstate "$STORE_PARAM" \
+	--pid "file=$PID_FILE" \
+	--ctrl "type=unixio,path=$SOCK_PATH" \
+	--log "file=$LOGFILE,level=20" \
 	--tpm2 \
-	${SWTPM_TEST_SECCOMP_OPT} &
+	${SWTPM_TEST_SECCOMP_OPT:+${SWTPM_TEST_SECCOMP_OPT}} &
 
-if wait_for_file $PID_FILE 3; then
+if wait_for_file "$PID_FILE" 3; then
 	echo "Error: (2) Socket TPM did not write pidfile."
 	exit 1
 fi
 
 echo "TPM re-started"
 
-PID="$(cat $PID_FILE)"
+PID="$(cat "$PID_FILE")"
 
 # Send TPM_Init
-act=$($SWTPM_IOCTL --unix $SOCK_PATH -i 2>&1)
+act=$($SWTPM_IOCTL --unix "$SOCK_PATH" -i 2>&1)
 if [ $? -ne 0 ]; then
 	echo "Error: $SWTPM_IOCTL CMD_INIT failed: $act"
-	cat $LOGFILE
+	cat "$LOGFILE"
 	exit 1
 fi
 
-${TOOLSPATH}/${PREFIX}startup -c
+"${TOOLSPATH}/${PREFIX}startup" -c
 if [ $? -ne 0 ]; then
 	echo "Error: tpm_startup clear failed."
-	cat $LOGFILE
+	cat "$LOGFILE"
 	exit 1
 fi
 
 fillup_nvram 0 1
 
-${TOOLSPATH}/${PREFIX}shutdown -c
+"${TOOLSPATH}/${PREFIX}shutdown" -c
 if [ $? -ne 0 ]; then
 	echo "Error: tpm_shutdown clear failed."
-	cat $LOGFILE
+	cat "$LOGFILE"
 	exit 1
 fi
 
 # Send Shutdown
-act=$($SWTPM_IOCTL --unix $SOCK_PATH -s 2>&1)
+act=$($SWTPM_IOCTL --unix "$SOCK_PATH" -s 2>&1)
 if [ $? -ne 0 ]; then
 	echo "Error: $SWTPM_IOCTL CMD_SHUTDOWN failed: $act"
 	exit 1
 fi
 
-echo "============================" >> $LOGFILE
+echo "============================" >> "$LOGFILE"
 
 echo "TPM was shut down"
 
 #################################################################
 # Run TPM2 with previously saved state and verify it's the same
 
-if [ ${SWTPM_TEST_LINEAR_FILE:-0} -ne 0 ]; then
+if [ "${SWTPM_TEST_LINEAR_FILE:-0}" -ne 0 ]; then
 	echo "Test 1 OK (skipped last with linear file)"
 	exit 0
 fi
 
-rm -f $TPMDIR/*
-cp -f ${TESTDIR}/data/tpm2state5/tpm2-00.permall $TPMDIR/tpm2-00.permall
-cp ${TESTDIR}/data/tpm2state5/signature.bin $SIGFILE
+rm -f "$TPMDIR"/*
+cp -f "${TESTDIR}/data/tpm2state5/tpm2-00.permall" "$TPMDIR/tpm2-00.permall"
+cp "${TESTDIR}/data/tpm2state5/signature.bin" "$SIGFILE"
 
 $SWTPM_EXE socket \
-	--server port=${TPM_COMMAND_PORT} \
-	--tpmstate $STORE_PARAM \
-	--pid file=$PID_FILE \
-	--ctrl type=unixio,path=$SOCK_PATH \
-	--log file=$LOGFILE,level=20 \
+	--server "port=${TPM_COMMAND_PORT}" \
+	--tpmstate "$STORE_PARAM" \
+	--pid "file=$PID_FILE" \
+	--ctrl "type=unixio,path=$SOCK_PATH" \
+	--log "file=$LOGFILE,level=20" \
 	--tpm2 \
-	${SWTPM_TEST_SECCOMP_OPT} &
+	${SWTPM_TEST_SECCOMP_OPT:+${SWTPM_TEST_SECCOMP_OPT}} &
 
-if wait_for_file $PID_FILE 3; then
+if wait_for_file "$PID_FILE" 3; then
 	echo "Error: (3) Socket TPM did not write pidfile."
 	exit 1
 fi
 
 echo "TPM started with previously generated state"
 
-PID="$(cat $PID_FILE)"
+PID="$(cat "$PID_FILE")"
 
 # Send TPM_Init
-act=$($SWTPM_IOCTL --unix $SOCK_PATH -i 2>&1)
+act=$($SWTPM_IOCTL --unix "$SOCK_PATH" -i 2>&1)
 if [ $? -ne 0 ]; then
 	echo "Error: $SWTPM_IOCTL CMD_INIT failed: $act"
 	exit 1
 fi
 
-${TOOLSPATH}/${PREFIX}startup -c
+"${TOOLSPATH}/${PREFIX}startup" -c
 if [ $? -ne 0 ]; then
 	echo "Error: tpm_startup clear failed."
-	cat $LOGFILE
+	cat "$LOGFILE"
 	exit 1
 fi
 
 fillup_nvram 0 1
 
-${TOOLSPATH}/${PREFIX}shutdown -c
+"${TOOLSPATH}/${PREFIX}shutdown" -c
 if [ $? -ne 0 ]; then
 	echo "Error: tpm_shutdown clear failed."
-	cat $LOGFILE
+	cat "$LOGFILE"
 	exit 1
 fi
 
 # Send Shutdown
-act=$($SWTPM_IOCTL --unix $SOCK_PATH -s 2>&1)
+act=$($SWTPM_IOCTL --unix "$SOCK_PATH" -s 2>&1)
 if [ $? -ne 0 ]; then
 	echo "Error: $SWTPM_IOCTL CMD_SHUTDOWN failed: $act"
 	exit 1
