Add ioctl to get configuration flags about keys in use
Add an ioctl that lets an application retrieve which keys are in use by the
TPM, i.e., file encryption or migration key

Signed-off-by: Stefan Berger <stefanb@linux.vnet.ibm.com>

diff --git a/tests/test_encrypted_state b/tests/test_encrypted_state
--- a/tests/test_encrypted_state
+++ b/tests/test_encrypted_state
@@ -111,7 +111,17 @@ if [ ! -r $VOLATILE_STATE_FILE ]; then
 	exit 1
 fi
 
-sleep 5
+tmp=$($CUSE_TPM_IOCTL -g /dev/$VTPM_NAME | cut -d":" -f2)
+if [ $? -ne 0 ]; then
+	echo "Error: Could not get the configration flags of the CUSE TPM."
+	exit 1
+fi
+
+if [ "$tmp" != " 0x1" ]; then
+	echo "Error: Unexpected configuration flags: $tmp; expected 0x1."
+	exit 1
+fi
+
 # Shut the TPM down
 exec 100>&-
 $CUSE_TPM_IOCTL -s /dev/$VTPM_NAME
