swtpm: integrity protect the encrypt TPM state
Integrity protect the TPM state when it is written in entrypted form.
libtpms state (for TPM1.2) is also integrity protecting the blobs, but
we better determine the integrity of the decrypted data on the layer
above it.

diff --git a/tests/test_encrypted_state b/tests/test_encrypted_state
--- a/tests/test_encrypted_state
+++ b/tests/test_encrypted_state
@@ -60,6 +60,10 @@ fi
 
 # Init the TPM
 $CUSE_TPM_IOCTL -i /dev/$VTPM_NAME
+if [ $? -ne 0 ]; then
+	echo "Error: CUSE TPM initialization failed."
+	exit 1
+fi
 
 sleep 0.5
 
@@ -133,6 +137,10 @@ fi
 
 # Init the TPM
 $CUSE_TPM_IOCTL -i /dev/$VTPM_NAME
+if [ $? -ne 0 ]; then
+	echo "Error: CUSE TPM initialization failed."
+	exit 1
+fi
 
 # Volatile state must have been removed by TPM now
 if [ -r $VOLATILE_STATE_FILE ]; then
@@ -162,6 +170,10 @@ fi
 
 # Send a new TPM_Init
 $CUSE_TPM_IOCTL -i /dev/$VTPM_NAME
+if [ $? -ne 0 ]; then
+	echo "Error: CUSE TPM initialization failed."
+	exit 1
+fi
 
 # Volatile state must have been removed by TPM now
 if [ -r $VOLATILE_STATE_FILE ]; then
@@ -182,7 +194,7 @@ if [ "$RES" != "$exp" ]; then
 fi
 
 
-# Finale shut down
+# Final shut down
 exec 100>&-
 $CUSE_TPM_IOCTL -s /dev/$VTPM_NAME
 
diff --git a/tests/test_resume_volatile b/tests/test_resume_volatile
--- a/tests/test_resume_volatile
+++ b/tests/test_resume_volatile
@@ -75,7 +75,7 @@ fi
 # Read PCR 10
 $ECHO -en '\x00\xC1\x00\x00\x00\x0E\x00\x00\x00\x15\x00\x00\x00\x0a' >&100
 RES=$(dd if=/proc/self/fd/100 2>/dev/null | od -t x1 -A n -w128)
-exp=' 00 c4 00 00 00 1e 00 00 00 00 6e dd 32 60 50 1d a3 2a de 90 a1 4c a3 10 df c3 a7 4f a0 04'
+exp=' 00 c4 00 00 00 1e 00 00 00 00 c7 8a 6e 94 c7 3c 4d 7f c3 05 c8 a6 6b bf 15 45 f4 ed b7 a5'
 if [ "$RES" != "$exp" ]; then
 	echo "Error: (1) Did not get expected result from TPM_PCRRead(10)"
 	echo "expected: $exp"
@@ -130,6 +130,10 @@ fi
 
 # Init the TPM
 $CUSE_TPM_IOCTL -i /dev/$VTPM_NAME
+if [ $? -ne 0 ]; then
+	echo "Error: CUSE TPM initialization failed."
+	exit 1
+fi
 
 sleep 0.5
 
@@ -146,7 +150,7 @@ exec 100<>/dev/$VTPM_NAME
 # Read PCR 10
 $ECHO -en '\x00\xC1\x00\x00\x00\x0E\x00\x00\x00\x15\x00\x00\x00\x0a' >&100
 RES=$(dd if=/proc/self/fd/100 2>/dev/null | od -t x1 -A n -w128)
-exp=' 00 c4 00 00 00 1e 00 00 00 00 6e dd 32 60 50 1d a3 2a de 90 a1 4c a3 10 df c3 a7 4f a0 04'
+exp=' 00 c4 00 00 00 1e 00 00 00 00 c7 8a 6e 94 c7 3c 4d 7f c3 05 c8 a6 6b bf 15 45 f4 ed b7 a5'
 if [ "$RES" != "$exp" ]; then
 	echo "Error: (1) Did not get expected result from TPM_PCRRead(10)"
 	echo "expected: $exp"
diff --git a/tests/test_save_load_encrypted_state b/tests/test_save_load_encrypted_state
--- a/tests/test_save_load_encrypted_state
+++ b/tests/test_save_load_encrypted_state
@@ -61,6 +61,10 @@ fi
 
 # Init the TPM
 $CUSE_TPM_IOCTL -i /dev/$VTPM_NAME
+if [ $? -ne 0 ]; then
+	echo "Error: CUSE TPM initialization failed."
+	exit 1
+fi
 
 sleep 0.5
 
@@ -196,6 +200,10 @@ fi
 
 # Send a new TPM_Init
 $CUSE_TPM_IOCTL -i /dev/$VTPM_NAME
+if [ $? -ne 0 ]; then
+	echo "Error: CUSE TPM initialization failed."
+	exit 1
+fi
 
 # Volatile state must have been removed by TPM now
 if [ -r $VOLATILE_STATE_FILE ]; then
