samples: Error out if key exists but is not readable for user
If the key is not readable as the current user, such as tss:tss,
but it is there, we don't try to create it but error out.

Signed-off-by: Stefan Berger <stefanb@linux.vnet.ibm.com>

diff --git a/samples/swtpm-localca b/samples/swtpm-localca
--- a/samples/swtpm-localca
+++ b/samples/swtpm-localca
@@ -386,6 +386,11 @@ main() {
 	fi
 
 	if [ ! -r "$SIGNKEY" ]; then
+		if [ -f "$SIGNKEY" ]; then
+			logerr "Signing key $SIGNKEY exists but cannot access" \
+			       "it as $(id -un):$(id -gn)."
+			exit 1
+		fi
 		# Create the signing key and issuer cert since it will be missing
 		logit "Creating root CA and a local CA's signing key and issuer cert."
 		create_localca_cert
