ci: add testing via docker compose
Auto testing as well as good example on:
how to run SWTPM in docker or compose.

Simply run `docker-compose up` to bring both swtpm and test.
Or run `docker-compose up --build --force-recreate` to re-build.
Or run `docker-compose up swtpm` to only start swtpm service without
test.

Added new job in the github action to automate this as well.

Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>

diff --git a/.github/workflows/docker.yaml b/.github/workflows/docker.yaml
--- a/.github/workflows/docker.yaml
+++ b/.github/workflows/docker.yaml
@@ -73,3 +73,32 @@ jobs:
           platforms: linux/amd64,linux/arm/v7,linux/arm/v6
           cache-from: type=gha
           cache-to: type=gha,mode=max
+
+  test:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: docker/setup-qemu-action@v3
+      - uses: docker/setup-buildx-action@v3.0.0
+      - name: Start containers
+        run: docker-compose up --build --force-recreate --detach
+      - name: Run Tests
+        run: |
+          set -x
+          docker-compose ps
+          name=$(docker-compose ps | grep swtpm-test | awk '{print $1}')
+          rc=$(docker wait "${name}")
+          if [ "${rc}" != "0" ]; then
+            echo "test failed:"
+            docker logs "${name}"
+            exit 1
+          fi
+
+      - name: Logs
+        if: always()
+        run: docker-compose logs
+
+      - name: Stop containers
+        if: always()
+        run: docker-compose down
+
